const tolstoy = {
    "nodes": [
        {
            "id": "1",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Иван",
            "ot": "Петрович",
            "dr": "1685-01-01",
            "ds": "1728-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "2",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Rtishcheva",
            "mfam": "",
            "name": "Прасковья",
            "ot": "Михайловна",
            "dr": "1693-01-01",
            "ds": "1748-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "3",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Shchetinin",
            "mfam": "",
            "name": "Иван",
            "ot": "Дмитриевич",
            "dr": "1690-01-01",
            "ds": "0000-00-00",
            "ts": "Н",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "4",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Gorchakov",
            "mfam": "",
            "name": "Иван",
            "ot": "Фёдорович",
            "dr": "1694-01-01",
            "ds": "1750-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "5",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Volkonsky",
            "mfam": "",
            "name": "Фёдор",
            "ot": "Михайлович",
            "dr": "1690-01-01",
            "ds": "1747-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "6",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Sontsova-Zasekina",
            "mfam": "",
            "name": "Анастасия",
            "ot": "Афанасьевна",
            "dr": "1700-01-01",
            "ds": "1760-01-01",
            "ts": "Н",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "7",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Trubetskoy",
            "mfam": "",
            "name": "Юрий",
            "ot": "Юрьевич",
            "dr": "1668-01-01",
            "ds": "1739-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "8",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Golovina",
            "mfam": "",
            "name": "Ольга",
            "ot": "Ивановна",
            "dr": "1704-01-01",
            "ds": "1760-01-01",
            "ts": "Н",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "9",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Odoevsky",
            "mfam": "",
            "name": "Иван",
            "ot": "Васильевич",
            "dr": "1710-01-01",
            "ds": "1768-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "10",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Tolstaya",
            "mfam": "",
            "name": "Прасковья",
            "ot": "Ивановна",
            "dr": "1709-01-01",
            "ds": "1758-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "11",
            "ido": "1",
            "idm": "2",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Андрей",
            "ot": "Иванович",
            "dr": "1721-01-01",
            "ds": "1803-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "12",
            "ido": "3",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Shchetinina",
            "mfam": "",
            "name": "Александра",
            "ot": "Ивановна",
            "dr": "1727-01-01",
            "ds": "1811-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "13",
            "ido": "4",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Gorchakov",
            "mfam": "",
            "name": "Николай",
            "ot": "Иванович",
            "dr": "1725-01-01",
            "ds": "1811-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "14",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Lukina",
            "mfam": "",
            "name": "Екатерина",
            "ot": "Александровна",
            "dr": "1730-01-01",
            "ds": "1815-01-01",
            "ts": "Н",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "15",
            "ido": "5",
            "idm": "6",
            "idd": "0",
            "idf": "0",
            "family": "Volkonsky",
            "mfam": "",
            "name": "Сергей",
            "ot": "Фёдорович",
            "dr": "1715-01-01",
            "ds": "1784-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "16",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "0",
            "family": "Chaadaeva",
            "mfam": "",
            "name": "Мария",
            "ot": "Дмитриевна",
            "dr": "1720-01-01",
            "ds": "1775-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "17",
            "ido": "7",
            "idm": "8",
            "idd": "0",
            "idf": "0",
            "family": "Trubetskoy",
            "mfam": "",
            "name": "Дмитрий",
            "ot": "Юрьевич",
            "dr": "1724-01-01",
            "ds": "1792-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "18",
            "ido": "9",
            "idm": "10",
            "idd": "0",
            "idf": "0",
            "family": "Odoevskaya",
            "mfam": "",
            "name": "Варвара",
            "ot": "Ивановна",
            "dr": "1725-01-01",
            "ds": "1788-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "19",
            "ido": "11",
            "idm": "12",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Илья",
            "ot": "Андреевич",
            "dr": "1757-01-01",
            "ds": "1820-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "20",
            "ido": "13",
            "idm": "14",
            "idd": "0",
            "idf": "0",
            "family": "Gorchakova",
            "mfam": "",
            "name": "Пелагея",
            "ot": "Николаевна",
            "dr": "1762-01-01",
            "ds": "1838-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "21",
            "ido": "15",
            "idm": "16",
            "idd": "0",
            "idf": "0",
            "family": "Volkonsky",
            "mfam": "",
            "name": "Николай",
            "ot": "Сергеевич",
            "dr": "1753-01-01",
            "ds": "1821-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "22",
            "ido": "17",
            "idm": "18",
            "idd": "0",
            "idf": "0",
            "family": "Trubetskaya",
            "mfam": "",
            "name": "Екатерина",
            "ot": "Дмитриевна",
            "dr": "1749-01-01",
            "ds": "1799-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "23",
            "ido": "19",
            "idm": "20",
            "idd": "0",
            "idf": "8",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Николай",
            "ot": "Ильич",
            "dr": "1794-06-26",
            "ds": "1837-07-21",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "24",
            "ido": "21",
            "idm": "22",
            "idd": "0",
            "idf": "13",
            "family": "Tolstaya",
            "mfam": "Volkonskaya",
            "name": "Мария",
            "ot": "Николаевна",
            "dr": "1790-01-01",
            "ds": "1830-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "25",
            "ido": "23",
            "idm": "24",
            "idd": "0",
            "idf": "21",
            "family": "Tolstoy",
            "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Leo_Tolstoy%2C_portrait.jpg/1200px-Leo_Tolstoy%2C_portrait.jpg",
            "mfam": "",
            "name": "Лев",
            "ot": "Николаевич",
            "dr": "1828-08-28",
            "ds": "1910-11-07",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "26",
            "ido": "23",
            "idm": "24",
            "idd": "0",
            "idf": "6",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Николай",
            "ot": "Николаевич",
            "dr": "1823-06-21",
            "ds": "0000-00-00",
            "ts": "Н",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "27",
            "ido": "23",
            "idm": "24",
            "idd": "0",
            "idf": "7",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Сергей",
            "ot": "Николаевич",
            "dr": "1826-02-17",
            "ds": "1904-08-23",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "28",
            "ido": "23",
            "idm": "24",
            "idd": "0",
            "idf": "4",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Дмитрий",
            "ot": "Николаевич",
            "dr": "1827-04-23",
            "ds": "1856-01-23",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "29",
            "ido": "23",
            "idm": "24",
            "idd": "0",
            "idf": "5",
            "family": "Tolstaya",
            "mfam": "",
            "name": "Мария",
            "ot": "Николаевна",
            "dr": "1830-01-01",
            "ds": "0000-00-00",
            "ts": "Н",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "30",
            "ido": "0",
            "idm": "0",
            "idd": "0",
            "idf": "12",
            "family": "Tolstaya",
            "mfam": "Берс",
            "name": "Софья",
            "ot": "Андреевна",
            "dr": "1844-08-22",
            "ds": "1919-11-04",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "31",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "17",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Сергей",
            "ot": "Львович",
            "dr": "1863-07-10",
            "ds": "1947-12-22",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "32",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "16",
            "family": "Sukhotina",
            "mfam": "Tolstaya",
            "name": "Татьяна",
            "ot": "Львовна",
            "dr": "1864-10-04",
            "ds": "1950-09-21",
            "ts": "Т",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "33",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "18",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Илья",
            "ot": "Львович",
            "dr": "1866-05-22",
            "ds": "1933-12-11",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "34",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "19",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Лев",
            "ot": "Львович",
            "dr": "1869-05-20",
            "ds": "1945-10-18",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "35",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "0",
            "family": "Obolenskaya",
            "mfam": "Tolstaya",
            "name": "Мария",
            "ot": "Львовна",
            "dr": "1871-01-01",
            "ds": "1906-01-01",
            "ts": "П",
            "cid": "",
            "ckey": "",
            "ccolor": "",
        },
        {
            "id": "36",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Пётр",
            "ot": "Львович",
            "dr": "1872-01-01",
            "ds": "1873-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "37",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Николай",
            "ot": "Львович",
            "dr": "1874-01-01",
            "ds": "1875-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "38",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "0",
            "family": "Tolstaya",
            "mfam": "",
            "name": "Варвара",
            "ot": "Львовна",
            "dr": "1875-01-01",
            "ds": "1875-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "39",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Андрей",
            "ot": "Львович",
            "dr": "1877-01-01",
            "ds": "1916-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "40",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Михаил",
            "ot": "Львович",
            "dr": "1879-01-01",
            "ds": "1944-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "41",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Алексей",
            "ot": "Львович",
            "dr": "1881-01-01",
            "ds": "1886-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "42",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "20",
            "family": "Tolstaya",
            "mfam": "",
            "name": "Александра",
            "ot": "Львовна",
            "dr": "1884-06-18",
            "ds": "1979-09-26",
            "ts": "Т",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
        {
            "id": "43",
            "ido": "25",
            "idm": "30",
            "idd": "0",
            "idf": "0",
            "family": "Tolstoy",
            "mfam": "",
            "name": "Иван",
            "ot": "Львович",
            "dr": "1888-01-01",
            "ds": "1895-01-01",
            "ts": "П",
            "cid": "1",
            "ckey": "Tolst",
            "ccolor": "#0033ff",
        },
    ],
    "links": [
        {
            "source": "1",
            "target": "11",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "2",
            "target": "11",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "3",
            "target": "12",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "4",
            "target": "13",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "5",
            "target": "15",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "6",
            "target": "15",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "7",
            "target": "17",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "8",
            "target": "17",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "9",
            "target": "18",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "10",
            "target": "18",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "11",
            "target": "19",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "12",
            "target": "19",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "13",
            "target": "20",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "14",
            "target": "20",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "15",
            "target": "21",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "16",
            "target": "21",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "17",
            "target": "22",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "18",
            "target": "22",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "19",
            "target": "23",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "20",
            "target": "23",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "21",
            "target": "24",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "22",
            "target": "24",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "23",
            "target": "25",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "24",
            "target": "25",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "23",
            "target": "26",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "24",
            "target": "26",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "23",
            "target": "27",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "24",
            "target": "27",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "23",
            "target": "28",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "24",
            "target": "28",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "23",
            "target": "29",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "24",
            "target": "29",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "31",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "31",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "32",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "32",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "33",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "33",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "34",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "34",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "35",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "35",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "36",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "36",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "37",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "37",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "38",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "38",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "39",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "39",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "40",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "40",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "41",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "41",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "42",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "42",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "25",
            "target": "43",
            "l": 1.5,
            "typ": 1,
        },
        {
            "source": "30",
            "target": "43",
            "l": 1.5,
            "typ": 1,
        },
    ],
};

export default tolstoy;